name: tugas_dari_ppt
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  sensors_plus: ^6.0.1
  camera: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true